# Logistic Regression
- Note:-  It is classification algorithm but internally uses linear model hence
name include Regression term.
- It also gives you probabilty regarding prediction.

# Logistic Regression for Binary Classification.

In [1]:
from sklearn.linear_model import LogisticRegression
import pandas as pd

In [7]:
df=pd.read_csv('G:/dataset/classification/fruits.csv')
df.FruitName=df.FruitName.map({'Apple':0,'Banana':1})
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [8]:
model=LogisticRegression()
model.fit(X,y)

LogisticRegression()

In [14]:
sample=[[3.1,50]]
print(model.predict(sample))
print(model.predict_proba(sample))

[1]
[[0.14627037 0.85372963]]


In [15]:
sample=[[4.2,76]]
print(model.predict(sample))
print(model.predict_proba(sample))

[1]
[[0.47294084 0.52705916]]


In [16]:
from sklearn.datasets import load_iris

In [24]:
iris=load_iris()
X=iris.data
y=iris.target
model=LogisticRegression(max_iter=200)
model.fit(X,y)

LogisticRegression(max_iter=200)

In [25]:
print(model.predict_proba([[.7,.1,2.5,1.1]]))
print(model.predict([[.7,.1,2.5,1.1]]))

[[0.7560245  0.24043857 0.00353693]]
[0]


# Maths behind LogisticRegression
- first it builds a linear model to find coefs and intercept
- then convert this linear model to non linear sothat it can perform classification.
- logit fun is used to convert linear part to non linear
- sigmoid & softmax are used as logit funs.
- with binary classification,sigmoid is used and with multiclass softmax is used.

In [26]:
df=pd.read_csv('G:/dataset/classification/fruits.csv')
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
model=LogisticRegression()
model.fit(X,y)

LogisticRegression()

In [29]:
coef=model.coef_
inter=model.intercept_
print('Coef:-  ',coef)
print('Intercept:-  ',inter)

Coef:-   [[-0.98526751 -0.02200081]]
Intercept:-   [5.91852746]


In [35]:
# It is a manual way to find linear part using y=mx+c
sample=[3,50]
z=coef[0][0]*3+coef[0][1]*50+inter
print(z)

[1.86268452]


In [36]:
print(model.decision_function([sample]))  #returns linear part of sample

[1.86268452]


In [37]:
import numpy as np

In [44]:
# Convert linear part to non_linear part using sigmoid function 1/(1+e^(-z)), here z is value of linear_part.
# its give probability of class 1
p_1=1/(1+np.exp(-z))
print(p_1)
if p_1<=.5:
    print('Apple')
else:
    print('Banana')

[0.86560954]
Banana


In [45]:
model.predict_proba([sample])

array([[0.13439046, 0.86560954]])

In [46]:
model.predict([sample])

array(['Banana'], dtype=object)

In [48]:
# Convert linear part to non_linear part using sigmoid function 1/(1+e^(z)), here z is value of linear_part.
# its give probability of class 0

p_1=1/(1+np.exp(z))
print(p_1)

p_0=1-p_1
print(p_0)

[0.13439046]
[0.86560954]


# Logistic Regression for Multi-Class Clssification.

In [49]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
import pandas as pd

In [51]:
iris=load_iris()
X=iris.data
y=iris.target
model=LogisticRegression(multi_class='ovr')
model.fit(X,y)

LogisticRegression(multi_class='ovr')

In [52]:
sample=[[1.5,.8,3.5,.9]]
print(model.predict(sample))
print(model.predict_proba(sample))

[1]
[[0.08289626 0.87528925 0.0418145 ]]


In [53]:
coef=model.coef_
inter=model.intercept_
print('Coef:-  ',coef)
print('Intercept:-  ',inter)

Coef:-   [[-0.44501376  0.89999242 -2.32353827 -0.97345836]
 [-0.1792787  -2.12866718  0.69665417 -1.27480129]
 [-0.39444787 -0.5133412   2.93087523  2.41709879]]
Intercept:-   [  6.69040651   5.58615272 -14.43121671]


In [55]:
z0=coef[0][0]*1.5+coef[0][1]*.8+coef[0][2]*3.5+coef[0][3]*.9+inter[0]
z1=coef[1][0]*1.5+coef[1][1]*.8+coef[1][2]*3.5+coef[1][3]*.9+inter[1]
z2=coef[2][0]*1.5+coef[2][1]*.8+coef[2][2]*3.5+coef[2][3]*.9+inter[2]
print(z0)
print(z1)
print(z2)

-2.265616650060048
4.90526936291506
-3.0001092547371258


In [56]:
model.decision_function(sample)

array([[-2.26561665,  4.90526936, -3.00010925]])

In [57]:
import numpy as np
p0=1/(1+np.exp(-z0))
p1=1/(1+np.exp(-z1))
p2=1/(1+np.exp(-z2))

#normalize probs
pn0=p0/(p0+p1+p2)
pn1=p1/(p0+p1+p2)
pn2=p2/(p0+p1+p2)
print(pn0,pn1,pn2)

0.08289625627733557 0.8752892457701095 0.041814497952554985


In [61]:
model.predict_proba(sample)

array([[0.08289626, 0.87528925, 0.0418145 ]])

In [63]:
iris=load_iris()
X=iris.data
y=iris.target
model=LogisticRegression(multi_class='multinomial',max_iter=200)
model.fit(X,y)

LogisticRegression(max_iter=200, multi_class='multinomial')

In [64]:
coef=model.coef_
inter=model.intercept_
print('Coef:-  ',coef)
print('Intercept:-  ',inter)

Coef:-   [[-0.42364806  0.96739434 -2.51708319 -1.07937296]
 [ 0.53447765 -0.3216458  -0.20639707 -0.94423775]
 [-0.11082959 -0.64574854  2.72348026  2.02361071]]
Intercept:-   [  9.84997373   2.23721656 -12.08719029]


In [65]:
sample=[[1.5,.8,3.5,.9]]
print(model.predict(sample))
print(model.predict_proba(sample))

[1]
[[0.25500582 0.69471992 0.05027426]]


In [71]:
# Solving Multi-Class problem using sigmoid function.
# Convert linear part to non_linear part using sigmoid function 1/(1+e^(-z)), here z is value of linear_part.
# its give probability of class 1

z0=coef[0][0]*1.5+coef[0][1]*.8+coef[0][2]*3.5+coef[0][3]*.9+inter[0]
z1=coef[1][0]*1.5+coef[1][1]*.8+coef[1][2]*3.5+coef[1][3]*.9+inter[1]
z2=coef[2][0]*1.5+coef[2][1]*.8+coef[2][2]*3.5+coef[2][3]*.9+inter[2]
print(z0)
print(z1)
print(z2)

0.20719027376778598
1.2094126761136526
-1.4166029498817156


In [72]:
model.decision_function(sample)

array([[ 0.20719027,  1.20941268, -1.41660295]])

In [73]:
# Convert linear part to non_linear part using softmax function e^(z0 or z1 or z2)/(e^z0+e^z1+e^z2), here z is value of linear_part.

p0=np.exp(z0)/(np.exp(z0)+np.exp(z1)+np.exp(z2))
p1=np.exp(z1)/(np.exp(z0)+np.exp(z1)+np.exp(z2))
p2=np.exp(z2)/(np.exp(z0)+np.exp(z1)+np.exp(z2))

print(p0)
print(p1)
print(p2)

0.255005821054618
0.694719922343499
0.05027425660188282


In [74]:
model.predict(sample)

array([1])

In [75]:
model.predict_proba(sample)

array([[0.25500582, 0.69471992, 0.05027426]])