In [1]:
if __name__ == '__main__':
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())
d=[[i,j,k] for i in range(x + 1) for j in range(y+1) for k in range(z+1)if (i+j+k) !=n]
print(d)

 1
 1
 1
 3


[[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1], [1, 0, 0], [1, 0, 1], [1, 1, 0]]


In [4]:
if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())
    p=[]
    p.append(arr)
    print(p)

 5
 2 3 6 6 5


In [1]:
if __name__ == '__main__':
    n=int(input('Enter the number of student:-'))
    p=[]
    for _ in range(n):
        name = input()
        score = float(input())
        p.append([name, score])
    p.sort(key=lambda x: (x[1], x[0]))
    q=sorted(set([score for name, score in p]))[1]
    for name, score in p:
        if score==q:
            print(name)

Enter the number of student:- 5
 Harry
 37.21
 Berry
 37.21
 Tina
 37.2
 Akriti
 41
 Harsh
 39


Berry
Harry


In [4]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()
    print(student_marks)

 3
 krishna 67 68 69
 arjun 70 98 63
 malika 52 56 60
 malik


{'krishna': [67.0, 68.0, 69.0], 'arjun': [70.0, 98.0, 63.0], 'malika': [52.0, 56.0, 60.0]}


In [5]:
if __name__ == '__main__':
    n = int(input())
    x=[]
    x.append(n)
    x

 1 2 3


ValueError: invalid literal for int() with base 10: '1 2 3'

In [10]:
import typing
n=int(input())
t=tuple(map(int, input().split()))
print(typing.uint(hash(t)))

 2
 1 2


AttributeError: module 'typing' has no attribute 'uint'

In [6]:
def divide_array(nums, k):
    nums.sort() 
    result = []
    current_array = []
    for num in nums:
        if not current_array: 
            current_array.append(num)
        elif num - current_array[0] <= k and len(current_array) < 3:
            current_array.append(num)
        else:
            if len(current_array) != 3:  
                return []
            result.append(current_array)
            current_array = [num]  
    if len(current_array) != 3: 
        return []
    result.append(current_array)
    return result

[]
[[1, 1, 3], [3, 4, 5], [7, 8, 9]]


In [3]:
x=[1,3,4,8,7,9,3,5,1]
print(x)
y=sorted(x)
len(y)


[1, 3, 4, 8, 7, 9, 3, 5, 1]


9

In [18]:
for i in range(1,5):
        print(i * (str(i) + ''))

1
22
333
4444


In [19]:
for i in range(1, 5):
    print(''.join([chr(48 + i)] * i))

1
22
333
4444


In [20]:
for i in range(1, 5):
    print((i * '1') if i == 1 else (i * '2') if i == 2 else (i * '3') if i == 3 else (i * '4'))

1
22
333
4444


In [22]:
for i in range(1, 5):
    print((i * (10 ** i - 1)) // 9)

1
22
333
4444


In [24]:
import math
import os
import random
import re
import sys


#
# Complete the 'efficientJanitor' function below.
#
# The function is expected to return an INTEGER.
# The function accepts FLOAT_ARRAY weight as parameter.
#

def efficientJanitor(weight):
    weight.sort()
    trip_count=0
    left=0
    right=len(weight)-1
    while left <= right:
        if weight[left] + weight[right] <= 3.00:
            left+=1
        right-=1
        trip_count=1
    return trip_count
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    weight_count = int(input().strip())

    weight = []

    for _ in range(weight_count):
        weight_item = float(input().strip())
        weight.append(weight_item)

    result = efficientJanitor(weight)
    print(result)

    fptr.write(str(result) + '\n')

    fptr.close()


KeyError: 'OUTPUT_PATH'

In [34]:
s='ABCDCDC'
x='CDC'
c=0
for i in range(len(x)-1):
    if x in s:
        c+=1
c

2

In [5]:
class pawan():
    def __init__(self):
        pass
    def personal_information(self):
        print('I am Pawan Yadav.\nI am an AI Engineer.\nMobile No:-8882293337\nCity:- Noida',sep='')
    def future_plan(self):
        print('I want to complete my M-Tech in Artificial Intelligence.\nThen after I want to do PHD in Artificial Intelligence.\nPAWAN YADAV..................',sep='')

In [8]:
c=pawan()
c.personal_information()
print('..........................................................................................................')
c.future_plan()

I am Pawan Yadav.
I am an AI Engineer.
Mobile No:-8882293337
City:- Noida
..........................................................................................................
I want to complete my M-Tech in Artificial Intelligence.
Then after I want to do PHD in Artificial Intelligence.
PAWAN YADAV..................


In [1]:
import calendar as cd
x=input().split()
y=cd.day_name()
y

 08 05 2020


TypeError: '_localized_day' object is not callable

In [2]:
import calendar

# Input format: "month day year"
input_date = input().strip()
month, day, year = map(int, input_date.split())

# Get the day of the week as an integer (0 for Monday, 1 for Tuesday, ..., 6 for Sunday)
day_of_week_index = calendar.weekday(year, month, day)

# Convert the day of the week index to the corresponding day name in uppercase
day_of_week = calendar.day_name[day_of_week_index].upper()

print(day_of_week)


 08 05 2024


MONDAY


### from datetime import datetime
import pytz

def get_absolute_time_difference(time1, time2):
    # Define a format string to parse the timestamps
    format_string = "%a %d %b %Y %H:%M:%S %z"
    
    # Parse the timestamps
    timestamp1 = datetime.strptime(time1, format_string)
    timestamp2 = datetime.strptime(time2, format_string)
    
    # Convert timestamps to UTC
    timestamp1_utc = timestamp1.astimezone(pytz.utc)
    timestamp2_utc = timestamp2.astimezone(pytz.utc)
    
    # Calculate the absolute difference in seconds
    difference_seconds = abs((timestamp1_utc - timestamp2_utc).total_seconds())
    
    return int(difference_seconds)

# Input number of test cases
test_cases = int(input().strip())

# Iterate through each test case
for _ in range(test_cases):
    # Input timestamps
    time1 = input().strip()
    time2 = input().strip()
    
    # Calculate and print the absolute difference
    print(get_absolute_time_difference(time1, time2))


In [10]:
t=int(input())
for i in range(t):
    x=input().split()
    a, b= x
    try:
        z=int(a)/int(b)
        print(z)
    except ZeroDivisionError as e:
        print('Error Code:', e)

 3
 4 2
 5 2
 6 2


3.0
3.0
3.0


In [11]:
def perform_integer_division(a, b):
    try:
        result = a // b
        print(result)
    except ZeroDivisionError:
        print("Error Code: integer division or modulo by zero")
    except ValueError:
        print("Error Code: invalid literal for int() with base 10:", b)
t = int(input())
for _ in range(t):
    a, b = input().split()
    try:
        a = int(a)
        b = int(b)
        perform_integer_division(a, b)
    except ValueError:
        print("Error Code: invalid literal for int() with base 10:", a)

 3
 1 0


Error Code: integer division or modulo by zero


 1 $


Error Code: invalid literal for int() with base 10: 1


 3 1


3


In [19]:
import numpy as np

x=input().split()
a, b, c=x
p=int(a)
q=int(b)
r=int(c)
print(p)
x=np.zeros((p, q, r))
y=np.ones((p, q, r))
print(x)
print(y)

 3 3 3


3
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [1]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
m=KNeighborsClassifier()