In [2]:
import pandas as pd
s=pd.Series([2,4,6,8,10])
print(s)

0     2
1     4
2     6
3     8
4    10
dtype: int64


In [6]:
import pandas as pd
s=pd.Series([2,4,6,8,10])
print(s)
print(type(s))
x=s.to_list()
print(x)
print(type(x))

0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
[2, 4, 6, 8, 10]
<class 'list'>


In [8]:
import pandas as pd
x=pd.Series([2, 4, 6, 8, 10])
y=pd.Series([1, 3, 5, 7, 9])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [12]:
import pandas as pd
x=pd.Series([2, 4, 6, 8, 10])
y=pd.Series([1, 3, 5, 7, 10])
print(x==y)
print(x>y)
print(x<y)

0    False
1    False
2    False
3    False
4     True
dtype: bool
0     True
1     True
2     True
3     True
4    False
dtype: bool
0    False
1    False
2    False
3    False
4    False
dtype: bool


In [15]:
import pandas as pd
x={'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
y=pd.Series(x)
print(y)

a    100
b    200
c    300
d    400
e    800
dtype: int64


In [22]:
import pandas as p
import numpy as np
x=np.array([10, 20, 30, 40, 50])
y=pd.Series(x)
print(y)

0    10
1    20
2    30
3    40
4    50
dtype: int32


In [26]:
import pandas as pd
x=pd.Series([100,200,'python',300.12,400])
y=pd.to_numeric(x,errors='coerce')
print(x)
print(y)

0       100
1       200
2    python
3    300.12
4       400
dtype: object
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64


In [30]:
import pandas as pd
x=pd.DataFrame({'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1, 11]})
y=x.iloc[:,0]
print(x)
print(type(x))
print(y)
print(type(y))

   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11
<class 'pandas.core.frame.DataFrame'>
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>


In [32]:
import pandas as pd
x= pd.Series([100,200,'python',300.12,400])
y=x.to_numpy()
print(x)
print(type(x))
print(y)
print(type(y))

0       100
1       200
2    python
3    300.12
4       400
dtype: object
<class 'pandas.core.series.Series'>
[100 200 'python' 300.12 400]
<class 'numpy.ndarray'>


In [38]:
import pandas as pd
x=pd.Series([
    ['Red', 'Green', 'White'],
    ['Red', 'Black'],
    ['Yellow']])
print(x)
y=x.apply(pd.Series).stack().reset_index(drop=True)
print(y)

0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object
        0      1      2
0     Red  Green  White
1     Red  Black    NaN
2  Yellow    NaN    NaN


In [2]:
import pandas as pd
x= pd.Series(['100','200','python','300.12','400'])
print(x.sort_values())

0       100
1       200
3    300.12
4       400
2    python
dtype: object


In [9]:
import pandas as pd
x= pd.Series(['100','200','python','300.12','400'])
y=pd.Series([500,'PHP'])
print(pd.concat([x,y],ignore_index=True))

0       100
1       200
2    python
3    300.12
4       400
5       500
6       PHP
dtype: object


In [10]:
import pandas as pd
x=pd.Series([0,1,2,3,4,5,6,7,8,9,10])
print(x)
n=6
y=x[x<n]
print(y)

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


In [2]:
import pandas as pd
x=pd.Series(data=[1,2,3,4,5],index=['A','B','C','D','E'])
print(x)
x=x.reindex(index=['B','A','C','D','E'])
print(x)

A    1
B    2
C    3
D    4
E    5
dtype: int64
B    2
A    1
C    3
D    4
E    5
dtype: int64


In [6]:
import pandas as pd
x=pd.Series(data=[1,2,3,4,5,6,7,8,9,5,3])
print("Original Data Series:")
print(x)
print("Mean of the said Data Series:")
print(x.mean())
print("Standard deviation of the said Data Series:")
print(x.std())

Original Data Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565


In [10]:
import pandas as pd
x=pd.Series([1,2,3,4,5])
y=pd.Series([2,4,6,8,10])
print(x[~x.isin(y)])

0    1
2    3
4    5
dtype: int64


In [13]:
import pandas as pd
import numpy as np
x=pd.Series([1,2,3,4,5])
y=pd.Series([2,4,6,8,10])
print(x)
print(y)
a=pd.Series(np.union1d(x,y))
b=pd.Series(np.intersect1d(x,y))
print(a[~a.isin(b)])

0    1
1    2
2    3
3    4
4    5
dtype: int64
0     2
1     4
2     6
3     8
4    10
dtype: int64
0     1
2     3
4     5
5     6
6     8
7    10
dtype: int64


In [15]:
import pandas as pd
import numpy as np
x=np.random.RandomState(100)
y=pd.Series(x.normal(10,4,20))
print(y)
print(np.percentile(y,q=[0,25,50,75,100]))

0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64
[ 3.00093811  8.09463867 10.23353705 12.21537733 14.61214321]


In [19]:
import pandas as pd
import numpy as np
x=pd.Series(np.take(list('0123456789'),np.random.randint(10,size=40)))
print(x)
print(x.value_counts())

0     2
1     9
2     2
3     9
4     6
5     5
6     4
7     4
8     4
9     0
10    8
11    0
12    6
13    1
14    0
15    8
16    9
17    1
18    9
19    2
20    5
21    7
22    3
23    1
24    8
25    8
26    7
27    5
28    6
29    3
30    1
31    8
32    2
33    6
34    5
35    5
36    1
37    5
38    8
39    2
dtype: object
5    6
8    6
2    5
1    5
9    4
6    4
4    3
0    3
7    2
3    2
dtype: int64


In [27]:
import pandas as pd
import numpy as np
x=pd.Series(np.random.randint(1,5,[15]))
print(x)
print("Top 2 Freq:", x.value_counts())
y=x[~x.isin(x.value_counts().index[:1])]='Other'
print(x)

0     2
1     4
2     3
3     3
4     3
5     2
6     3
7     3
8     1
9     1
10    3
11    3
12    4
13    4
14    4
dtype: int32
Top 2 Freq: 3    7
4    4
2    2
1    2
dtype: int64
0     Other
1     Other
2         3
3         3
4         3
5     Other
6         3
7         3
8     Other
9     Other
10        3
11        3
12    Other
13    Other
14    Other
dtype: object


In [31]:
import pandas as pd
import numpy as np
x=pd.Series([1,9,5,6,9,7,1,1,1])
print(x)
y=np.where(x%5==0)
print(y)

0    1
1    9
2    5
3    6
4    9
5    7
6    1
7    1
8    1
dtype: int64
(array([2], dtype=int64),)


In [32]:
import pandas as pd
x=pd.Series(list('2390238923902390239023'))
y=[0,2,6,11,21]
print(x)
r=x.take(y)
print(r)

0     2
1     3
2     9
3     0
4     2
5     3
6     8
7     9
8     2
9     3
10    9
11    0
12    2
13    3
14    9
15    0
16    2
17    3
18    9
19    0
20    2
21    3
dtype: object
0     2
2     9
6     8
11    0
21    3
dtype: object


In [33]:
import pandas as pd
x=pd.Series([1,2,3,4,5,6,7,8,9,10])
y=pd.Series([1,3,5,7,10])
print(x)
print(y)
print([pd.Index(x).get_loc(i) for i in y])

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
0     1
1     3
2     5
3     7
4    10
dtype: int64
[0, 2, 4, 6, 9]


In [35]:
import pandas as pd
x=pd.Series(['php','python','java','c#'])
print(x)
print(x.map(lambda i:i[0].upper() +i[1:-1]+i[-1].upper()))

0       php
1    python
2      java
3        c#
dtype: object
0       PhP
1    PythoN
2      JavA
3        C#
dtype: object


In [36]:
import pandas as pd
x=pd.Series(['php','python','java','c#'])
print(x)
print(x.map(lambda i:len(i)))

0       php
1    python
2      java
3        c#
dtype: object
0    3
1    6
2    4
3    2
dtype: int64


In [38]:
import pandas as pd
x=pd.Series([1,3,5,8,10,11,15])
print(x)
print(x.diff().tolist())
print(x.diff().diff().tolist())

0     1
1     3
2     5
3     8
4    10
5    11
6    15
dtype: int64
[nan, 2.0, 2.0, 3.0, 2.0, 1.0, 4.0]
[nan, nan, 0.0, 1.0, -1.0, -1.0, 3.0]


In [39]:
import pandas as pd
x=pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])
print(x)
print(pd.to_datetime(x))

0         01 Jan 2015
1          10-02-2016
2            20180307
3          2014/05/06
4          2016-04-12
5    2019-04-06T11:20
dtype: object
0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]


In [54]:
import pandas as pd
from dateutil.parser import parse
x=pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])
print(x)
x=(x.map(lambda i: parse(i)))
print(x.dt.day.tolist())
print(x.dt.dayofyear.tolist())
print(x.dt.isocalendar().week.tolist())
print(x.dt.strftime('%A').tolist())

0         01 Jan 2015
1          10-02-2016
2            20180307
3          2014/05/06
4          2016-04-12
5    2019-04-06T11:20
dtype: object
[1, 2, 7, 6, 12, 6]
[1, 276, 66, 126, 103, 96]
[1, 39, 10, 19, 15, 14]
['Thursday', 'Sunday', 'Wednesday', 'Tuesday', 'Tuesday', 'Saturday']


In [56]:
import pandas as pd
from dateutil.parser import parse
x=pd.Series(['Jan 2015', 'Feb 2016', 'Aug 2017', 'Apr 2018', 'May 2019'])
print(x)
print(x.map(lambda i: parse('22' + i)))

0    Jan 2015
1    Feb 2016
2    Aug 2017
3    Apr 2018
4    May 2019
dtype: object
0   2015-01-22
1   2016-02-22
2   2017-08-22
3   2018-04-22
4   2019-05-22
dtype: datetime64[ns]


In [64]:
import pandas as pd
from collections import Counter
x=pd.Series(['Red','Green','Orange','Pink','Yellow','White'])
print(x)
print(x[x.map(lambda i: sum([Counter(i.lower()).get(j,0) for j in list('aeiou')])>=2)])

0       Red
1     Green
2    Orange
3      Pink
4    Yellow
5     White
dtype: object
1     Green
2    Orange
4    Yellow
5     White
dtype: object


In [66]:
import pandas as pd
import numpy as np
x=pd.Series([1,2,3,4,5,6,7,8,9,10])
y=pd.Series([11,8,7,5,6,5,3,4,7,1])
print(x)
print(y)
print(np.linalg.norm(x-y))

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
0    11
1     8
2     7
3     5
4     6
5     5
6     3
7     4
8     7
9     1
dtype: int64
16.492422502470642


In [67]:
import pandas as pd
import numpy as np
x=pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
print(x)
t=np.diff(np.sign(np.diff(x)))
r=np.where(t== -2)[0]+1
print(r)

0    1
1    8
2    7
3    5
4    6
5    5
6    3
7    4
8    7
9    1
dtype: int64
[1 4 8]


In [72]:
import pandas as pd
x='abc def abcdef icd'
y=pd.Series(list(x))
e=y.value_counts()
c=e.dropna().index[-1]
r=''.join(y.replace(' ',c))
print(x,'\n',e,'\n',c,'\n',r,sep='')

abc def abcdef icd
c    3
     3
d    3
a    2
b    2
e    2
f    2
i    1
dtype: int64
i
abcidefiabcdefiicd


In [79]:
import pandas as pd
import numpy as np
x=pd.Series(np.arange(15)+np.random.normal(1,10,15))
print(x)
print([x.autocorr(i).round(2) for i in range(11)][1:])

0    -30.840509
1    -10.673720
2      1.674991
3     13.475263
4     -3.552686
5     -3.974088
6      9.656217
7     -1.776251
8      3.430074
9     11.317052
10    -0.254612
11    14.588502
12    10.653032
13    10.679616
14    13.619111
dtype: float64
[0.44, 0.11, 0.2, 0.32, 0.52, 0.22, 0.36, 0.5, 0.18, 0.67]


In [80]:
import pandas as pd
x=pd.Series(pd.date_range('2024-01-01',periods=52,freq='W-SUN'))
print(x)

0    2024-01-07
1    2024-01-14
2    2024-01-21
3    2024-01-28
4    2024-02-04
5    2024-02-11
6    2024-02-18
7    2024-02-25
8    2024-03-03
9    2024-03-10
10   2024-03-17
11   2024-03-24
12   2024-03-31
13   2024-04-07
14   2024-04-14
15   2024-04-21
16   2024-04-28
17   2024-05-05
18   2024-05-12
19   2024-05-19
20   2024-05-26
21   2024-06-02
22   2024-06-09
23   2024-06-16
24   2024-06-23
25   2024-06-30
26   2024-07-07
27   2024-07-14
28   2024-07-21
29   2024-07-28
30   2024-08-04
31   2024-08-11
32   2024-08-18
33   2024-08-25
34   2024-09-01
35   2024-09-08
36   2024-09-15
37   2024-09-22
38   2024-09-29
39   2024-10-06
40   2024-10-13
41   2024-10-20
42   2024-10-27
43   2024-11-03
44   2024-11-10
45   2024-11-17
46   2024-11-24
47   2024-12-01
48   2024-12-08
49   2024-12-15
50   2024-12-22
51   2024-12-29
dtype: datetime64[ns]


In [83]:
import pandas as pd
import numpy as np
c=list('ABCDEFGHIJKLMNOP')
n=np.arange(8)
m=dict(zip(c,n))
x=pd.Series(m)
y=x.to_frame().reset_index()
print(y.head())

  index  0
0     A  0
1     B  1
2     C  2
3     D  3
4     E  4


In [87]:
import pandas as pd
x=pd.Series(range(10))
y=pd.Series(list('pqrstuvwxy'))
df=pd.concat([x,y],axis=1)
print(df)

   0  1
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y


In [89]:
import pandas as pd
x=pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
y = pd.Series([1, 8, 7, 5, 6, 0, 3, 4, 7, 1])
print(x==y)

0     True
1     True
2     True
3     True
4     True
5    False
6     True
7     True
8     True
9     True
dtype: bool


In [91]:
import pandas as pd
x=pd.Series([1, 3, 7, 12, 88, 23, 3, 1, 9, 0])
print(x.idxmax())
print(x.idxmin())

4
9


In [93]:
import pandas as pd
x=pd.Series([68, 75, 86, 80, None])
y=pd.DataFrame({'W':[68,75,86,80,None],'X':[78,75,None,80,86], 'Y':[84,94,89,86,86],'Z':[86,97,96,72,83]})
print(x)
print(y)
print(y.ne(x,axis=0))

0    68.0
1    75.0
2    86.0
3    80.0
4     NaN
dtype: float64
      W     X   Y   Z
0  68.0  78.0  84  86
1  75.0  75.0  94  97
2  86.0   NaN  89  96
3  80.0  80.0  86  72
4   NaN  86.0  86  83
       W      X     Y     Z
0  False   True  True  True
1  False  False  True  True
2  False   True  True  True
3  False  False  True  True
4   True   True  True  True
