In [5]:
import numpy as np
z=np.__version__
print(z)
print(np.show_config())

1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/panka/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/panka/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/panka/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/panka/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/panka/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/panka/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/panka/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/panka/anacond

In [6]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [9]:
import numpy as np
x=np.array([1,2,3,4,5,6])
print('Original array:\n',x,sep='')
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x=np.array([0,1,2,3])
print('Original array:\n',x,sep='')
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array:
[1 2 3 4 5 6]
Test if none of the elements of the said array is zero:
True
Original array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False


In [15]:
import numpy as np
x=np.array([1,0,0,0])
print('Original array:\n',x,sep='')
print("Test if none of the elements of the said array is non-zero:")
print(np.any(x))
x=np.array([0,0,0,0])
print('Original array:\n',x,sep='')
print("Test if none of the elements of the said array is non-zero:")
print(np.any(x))

Original array:
[1 0 0 0]
Test if none of the elements of the said array is non-zero:
True
Original array:
[0 0 0 0]
Test if none of the elements of the said array is non-zero:
False


In [12]:
import numpy as np
x=np.array([1,0,np.nan,np.inf])
print('Original array:\n',x,sep='')
print("Test a given array element-wise for finiteness :")
print(np.isfinite(x))

Original array:
[ 1.  0. nan inf]
Test if none of the elements of the said array is zero:
[ True  True False False]


In [13]:
import numpy as np
x=np.array([1,0,np.nan,np.inf])
print('Original array:\n',x,sep='')
print("Test element-wise for positive or negative infinity:")
print(np.isinf(x))

Original array:
[ 1.  0. nan inf]
Test if none of the elements of the said array is zero:
[False False False  True]


In [14]:
import numpy as np
x=np.array([1,0,np.nan,np.inf])
print('Original array:\n',x,sep='')
print("Test element-wise for NaN:")
print(np.isnan(x))

Original array:
[ 1.  0. nan inf]
Test if none of the elements of the said array is zero:
[False False  True False]


In [16]:
import numpy as np
x=np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print('Original array:\n',x,sep='')
print("Checking for complex number:")
print(np.iscomplex(x))
print('Checking for real number:')
print(np.isreal(x))
print("Checking for scalar type:")
print(np.isscalar(3.1))
print(np.isscalar([3.1])) 

Original array:
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number:
[ True False False False False  True]
Checking for real number:
[False  True  True  True  True False]
Checking for scalar type:
True
False


In [17]:
import numpy as np
print("Test if two arrays are element-wise equal within a tolerance:")
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True)) 

Test if two arrays are element-wise equal within a tolerance:
False
True
False
False
True


In [19]:
import numpy as np
x=np.array([3,5])
y=np.array([2,5])
print('Original numbers:')
print(x)
print(y)
print('Comparison -greater')
print(np.greater(x,y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison -greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


In [4]:
import numpy as np
x=np.array([3,5])
y=np.array([2,5])
z=np.array([3,5])
print('Original numbers:')
print(x)
print(y)
print(np.equal(x,y))
print(np.allclose(x,y))
print(np.allclose(x,z))

Original numbers:
[3 5]
[2 5]
[False  True]
False
True


In [9]:
import numpy as np
x=np.array([1, 7, 13, 105])
print(x)
print('%d bytes'%(x.size * x.itemsize))

[  1   7  13 105]
16 bytes


In [93]:
import numpy as np
x=np.zeros(10)
print(x)
y=np.ones(10)
print(y)
z=np.full(10,5,dtype=float)
print(z)
p=np.ones(10)*5
print(p)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [21]:
import numpy as np
x=np.arange(30,70)
print(x)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [31]:
import numpy as np
x=np.arange(30,71,2)
print("Array of all the even integers from 30 to 70")
print(x)
#############################################################################
print('.....................................................................')
x=np.arange(31,71,2)
print("Array of all the odd integers from 30 to 70")
print(x)

Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]
.....................................................................
Array of all the odd integers from 30 to 70
[31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69]


In [37]:
import numpy as np
x=np.identity(3)
print('3X3 Matrix:')
print(x)

3X3 Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [53]:
import numpy as np
x=np.random.normal(0,1,1)
print(x)

[1.70795907]


In [55]:
import numpy as np
x=np.random.normal(0,1,15)
print(x)

[ 1.07531259  0.92885207  0.25953037  0.01356636  1.62907682  0.51371054
  1.04790695  0.39054823 -0.76027249 -0.97728996  0.64439387  1.17551911
 -1.10698265  0.88558358 -2.75601726]


In [58]:
import numpy as np
x=np.arange(15,55)
print("Original vector:")
print(x)
print("All values except the first and last of the said vector:")
print(x[1:-1])

Original vector:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
All values except the first and last of the said vector:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [63]:
import numpy as np
x=np.arange(10,22).reshape((3,4))
print(x)
for i in np.nditer(x):
    print(i,end=' ')

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
10 11 12 13 14 15 16 17 18 19 20 21 

In [66]:
import numpy as np
x=np.linspace(5,50,10)
print(x)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [67]:
import numpy as np
x= np.arange(21)
print(x)
x[(x>=9) & (x<=15)]*=-1
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [69]:
import numpy as np
x=np.random.randint(0,10,5)
print(x)

[0 9 5 8 6]


In [75]:
import numpy as np
x=np.array([5,11,4,6,5])
y=np.array([10,7,9,4,8])
z=x * y
print(z)

[50 77 36 24 40]


In [78]:
import numpy as np
x=np.arange(10,22).reshape((3,4))
print(x)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [83]:
import numpy as np
x=np.array([[10, 11, 12, 13],
 [14, 15, 16, 17]])
print(x.shape)

(2, 4)


In [91]:
import numpy as np
x=np.identity(3)
print(x)
#########################################################################
print('..................................................................')
x=np.eye(3,3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
..................................................................
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [100]:
import numpy as np
x=np.ones((10,10))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [110]:
import numpy as np
x=np.diag([1,2,3,4,5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [135]:
import numpy as np
x=np.zeros((4,4))
x[::2,1::2]=1
x[1::2,::2]=1
print(x)
#############################################################################
print('.....................................................................')
x=np.zeros((4,4))
x[::2,1::2]=1
x[1::2,::2]=1
x[0][2]=1
x[1][3]=1
x[2][0]=1
x[3][1]=1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]
.....................................................................
[[0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 0.]]
