In [1]:
import numpy as np

In [8]:
x=np.array([[2,3],[4,5]])
y=np.array([[6,1],[7,8]])
z=x*y
print(z)
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
z=np.dot(p,q)
z

[[12  3]
 [28 40]]


array([[1, 2],
       [3, 4]])

In [10]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
z=np.outer(p,q)
z

array([[1, 2, 3, 4],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 2, 3, 4]])

In [12]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
z=np.cross(p,q)
print(z)
z=np.cross(q,p)
print(z)

[ 2 -3]
[-2  3]


In [16]:
import numpy as np
a = np.array([[1, 0], [1, 2]])
print("Original 2-d array")
print(a)
z=np.linalg.det(a)
z

Original 2-d array
[[1 0]
 [1 2]]


2.0

In [20]:
import numpy as np
a = np.array([1,2,3])
b = np.array([0,1,0])
print("Original 2-d array")
print(a)
print(b)
print(np.einsum('n,n',a,b))
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Original Higher dimension:")
print(x)
print(y)
result = np.einsum("mk,kn", x, y)
print("Einstein’s summation convention of the said arrays:")
print(result) 

Original 2-d array
[1 2 3]
[0 1 0]
2
Original Higher dimension:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Einstein’s summation convention of the said arrays:
[[ 24  27  30]
 [ 78  90 102]
 [132 153 174]]


In [23]:
import numpy as np
a = np.array([1, 2, 5])
b = np.array([2, 1, 0])
print("Original 1-d arrays:")
print(a)
print(b)
z=np.inner(a,b)
print(z)
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
np.inner(x,y)

Original 1-d arrays:
[1 2 5]
[2 1 0]
4


array([[ 14,  23,  32],
       [ 50,  86, 122],
       [ 86, 149, 212]])

In [28]:
import numpy as np
m = np.mat("3 -2; 1 0")
print("Original matrix:")
print("a\n", m)
w,v=np.linalg.eig(m)
print("Eigenvalues of the said matrix", w)
print("Eigenvectors of the said matrix", v) 

Original matrix:
a
 [[ 3 -2]
 [ 1  0]]
Eigenvalues of the said matrix [2. 1.]
Eigenvectors of the said matrix [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [33]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([0, 1, 0])
print("Original 1-d arrays:")
print(a)
print(b)
z=np.kron(a,b)
print(z)
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Original Higher dimension:")
print(x)
print(y)
np.kron(x,y)

Original 1-d arrays:
[1 2 3]
[0 1 0]
[0 1 0 0 2 0 0 3 0]
Original Higher dimension:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 0,  0,  0,  3,  4,  5,  6,  8, 10],
       [ 0,  0,  0,  6,  7,  8, 12, 14, 16],
       [ 0,  0,  0,  9, 10, 11, 18, 20, 22],
       [ 9, 12, 15, 12, 16, 20, 15, 20, 25],
       [18, 21, 24, 24, 28, 32, 30, 35, 40],
       [27, 30, 33, 36, 40, 44, 45, 50, 55],
       [18, 24, 30, 21, 28, 35, 24, 32, 40],
       [36, 42, 48, 42, 49, 56, 48, 56, 64],
       [54, 60, 66, 63, 70, 77, 72, 80, 88]])

In [36]:
import numpy as np
a = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])
print(a)
np.linalg.cond(a)

[[ 1  0 -1]
 [ 0  1  0]
 [ 1  0  1]]


1.4142135623730951

In [37]:
import numpy as np
v = np.arange(7)
result = np.linalg.norm(v)
print("Vector norm:")
print(result)
m = np.matrix('1, 2; 3, 4') 
result1 = np.linalg.norm(m)
print("Matrix norm:")
print(result1)

Vector norm:
9.539392014169456
Matrix norm:
5.477225575051661


In [38]:
import numpy as np
a = np.array([[1,2],[3,4]])
print("Original array:")
print(a)
np.linalg.det(a)

Original array:
[[1 2]
 [3 4]]


-2.0000000000000004

In [40]:
import numpy as np
m = np.matrix('1, 2; 3, 4') 
print(m)
np.linalg.inv(m)

[[1 2]
 [3 4]]


matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [42]:
import numpy as np
m = np.matrix('1, 2; 3, 4') 
print(m)
print(np.linalg.qr(m))

[[1 2]
 [3 4]]
QRResult(Q=matrix([[-0.31622777, -0.9486833 ],
        [-0.9486833 ,  0.31622777]]), R=matrix([[-3.16227766, -4.42718872],
        [ 0.        , -0.63245553]]))


In [43]:
import numpy as np
m = np.matrix('1, 2; 3, 4') 
print(m)
print(np.linalg.cond(m))

[[1 2]
 [3 4]]
14.933034373659265


In [45]:
import numpy as np
m = np.matrix('1, 2; 3, 4') 
print(m)
print(np.trace(m))

[[1 2]
 [3 4]]
5


In [48]:
import numpy as np
a = np.array([[4, 12, -16], [12, 37, -53], [-16, -53, 98]], dtype=np.int32)
print("Original array:")
print(a)
print(np.linalg.cholesky(a))

Original array:
[[  4  12 -16]
 [ 12  37 -53]
 [-16 -53  98]]
[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8. -5.  3.]]


In [50]:
import numpy as np
a = np.array([[4, 12, -16], [12, 37, -53], [-16, -53, 98]], dtype=np.int32)
print("Original array:")
print(a)
q, r = np.linalg.qr(a)
print("qr factorization of the said array:")
print("q=\n", q, "\nr=\n", r) 

Original array:
[[  4  12 -16]
 [ 12  37 -53]
 [-16 -53  98]]
qr factorization of the said array:
q=
 [[-0.19611614 -0.37203388  0.90726471]
 [-0.58834841 -0.69554161 -0.41239305]
 [ 0.78446454 -0.61466468 -0.08247861]] 
r=
 [[-20.39607805 -65.69890527 111.19784862]
 [  0.           2.37778177 -17.42089094]
 [  0.           0.          -0.74230749]]


In [52]:
import numpy as np
a = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
print("Original array:")
print(a)
U, s, V = np.linalg.svd(a, full_matrices=False)
q, r = np.linalg.qr(a)
print("Factor of a given array by Singular Value Decomposition:")
print("U=\n", U, "\ns=\n", s, "\nV=\n", V) 

Original array:
[[1. 0. 0. 0. 2.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]]
Factor of a given array by Singular Value Decomposition:
U=
 [[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]] 
s=
 [3.       2.236068 2.       0.      ] 
V=
 [[-0.         0.         1.         0.         0.       ]
 [ 0.4472136  0.         0.         0.         0.8944272]
 [-0.         1.         0.         0.         0.       ]
 [ 0.         0.         0.         1.         0.       ]]


In [57]:
import numpy as np
a = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(a)
print(np.linalg.cond(a,'fro'))
print(np.linalg.norm(a,'fro'))

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3.193239515623568e+17
16.881943016134134
