In [1]:
import numpy as np

In [2]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
arr=arr.reshape(2,-1)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
a=np.random.random((5,3))
b=np.random.random((3,2))
result=np.dot(a,b)
result

array([[1.34685428, 1.0128427 ],
       [1.03672867, 0.84126296],
       [1.38584044, 0.89003654],
       [1.06002517, 0.83190154],
       [1.38109347, 1.05809646]])

In [5]:
arr=np.arange(10)
arr[arr%2!=0]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [6]:
arr=np.array([-1,2,0,-4,5])
bool=arr>0
bool

array([False,  True, False, False,  True])

In [7]:
arr=np.arange(1,10)
arr[arr%2==0]*=-1
arr

array([ 1, -2,  3, -4,  5, -6,  7, -8,  9])

In [8]:
a=np.random.random((3,3))
norm=(a-np.mean(a))/np.std(a)
norm

array([[-1.11997959,  1.36152785, -0.30939429],
       [ 0.91010636,  0.37074475, -1.51567249],
       [-0.91247125,  1.30120817, -0.0860695 ]])

In [9]:
m=np.random.random((3,3))
di_sum=np.trace(m)
di_sum

2.062671403112638

In [10]:
x=np.array([1,2,0,0,4,0])
n=np.nonzero(x)
n

(array([0, 1, 4], dtype=int64),)