In [1]:
import numpy as np

In [2]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
arr=arr.reshape(2,-1)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
a=np.random.random((5,3))
b=np.random.random((3,2))
result=np.dot(a,b)
result

array([[0.56441759, 1.17652384],
       [0.81639506, 1.25698927],
       [0.89755716, 1.27795848],
       [0.84154041, 1.2656112 ],
       [0.71171422, 0.77947889]])

In [15]:
arr=np.arange(10)
arr[arr%2!=0]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [16]:
arr=np.array([-1,2,0,-4,5])
bool=arr>0
bool

array([False,  True, False, False,  True])

In [20]:
arr=np.arange(1,10)
arr[arr%2==0]*=-1
arr

array([ 1, -2,  3, -4,  5, -6,  7, -8,  9])

In [22]:
a=np.random.random((3,3))
norm=(a-np.mean(a))/np.std(a)
norm

array([[-1.46873524,  1.32159811,  0.35683106],
       [-0.08595178, -1.43550268,  0.43631749],
       [ 0.29144092,  1.39992055, -0.81591841]])

In [23]:
m=np.random.random((3,3))
di_sum=np.trace(m)
di_sum

0.6836442784877755

In [24]:
x=np.array([1,2,0,0,4,0])
n=np.nonzero(x)
n

(array([0, 1, 4], dtype=int64),)