In [4]:
import numpy as np
a=np.random.normal(size=5)
a

array([ 1.4028523 ,  0.82596358, -0.60610482, -1.18538772,  1.00465847])

In [6]:
import numpy as np
a=np.random.randint(10,30,6)
a

array([22, 12, 18, 20, 18, 19])

In [8]:
import numpy as np
a=np.random.random((3,3,3))
a

array([[[0.6538771 , 0.10166742, 0.27757442],
        [0.75954702, 0.60071892, 0.42164452],
        [0.16900006, 0.96078281, 0.93983606]],

       [[0.98321266, 0.02741024, 0.07856421],
        [0.9907323 , 0.66987309, 0.83046328],
        [0.61076113, 0.44539943, 0.70297251]],

       [[0.8961556 , 0.41694747, 0.71288738],
        [0.62777947, 0.63269722, 0.93000548],
        [0.47839954, 0.86296073, 0.82716188]]])

In [11]:
import numpy as np
a=np.random.random((5,5))
print(a)
print(np.min(a))
print(np.max(a))

[[0.6350622  0.96543539 0.66880504 0.18930741 0.8189192 ]
 [0.6717754  0.87213902 0.19773115 0.3188604  0.66973657]
 [0.96730712 0.11572966 0.22384084 0.64365708 0.27772004]
 [0.11202343 0.54495604 0.4749619  0.90068769 0.33264765]
 [0.53550694 0.89375622 0.83437923 0.67239406 0.3663504 ]]
0.11202343160438277
0.9673071170840636


In [15]:
import numpy as np
a=np.random.random((10,4))
b=a[:5]
print(a)
print(b)

[[0.96945264 0.96071198 0.15934488 0.16656166]
 [0.15075809 0.35348188 0.74192866 0.13193628]
 [0.01344448 0.96051571 0.85240222 0.03364774]
 [0.96293106 0.79961894 0.00553913 0.86491586]
 [0.35769121 0.6692886  0.03778606 0.95755614]
 [0.56400337 0.55530892 0.58944642 0.98664066]
 [0.10717942 0.28099415 0.00579536 0.02728934]
 [0.2734313  0.59628345 0.21808335 0.32260966]
 [0.69989735 0.31577989 0.80648762 0.0143259 ]
 [0.93766308 0.41940933 0.76008864 0.46407825]]
[[0.96945264 0.96071198 0.15934488 0.16656166]
 [0.15075809 0.35348188 0.74192866 0.13193628]
 [0.01344448 0.96051571 0.85240222 0.03364774]
 [0.96293106 0.79961894 0.00553913 0.86491586]
 [0.35769121 0.6692886  0.03778606 0.95755614]]


In [22]:
import numpy as np
x=np.arange(0,10)
np.random.shuffle(x)
print(x)
print(np.random.permutation(10))

[3 2 4 1 7 8 6 9 0 5]
[3 5 7 4 0 6 9 1 2 8]


In [31]:
import numpy as np
x=np.random.random((3,3))
print(x)
y=(x-x.min())/(x.max()-x.min())
print(y)

[[0.65379812 0.94799862 0.38142695]
 [0.51261477 0.09204315 0.23740229]
 [0.26485167 0.66253433 0.27360635]]
[[0.65628994 1.         0.33808278]
 [0.49134755 0.         0.16982091]
 [0.20188961 0.66649633 0.21211757]]


In [38]:
import numpy as np
x=np.random.random(10)
print(x)
np.sort(x)

[0.77341317 0.80997777 0.10164584 0.6831906  0.10453822 0.65530181
 0.05776268 0.40318263 0.41093117 0.36029569]


array([0.05776268, 0.10164584, 0.10453822, 0.36029569, 0.40318263,
       0.41093117, 0.65530181, 0.6831906 , 0.77341317, 0.80997777])

In [39]:
import numpy as np
x=np.random.uniform(1,12,5)
v=4
n=x.flat[np.abs(x-v).argmin()]
print(n)

3.395654602874778


In [44]:
import numpy as np
x=np.random.randint(0,2,size=5)
y=np.random.randint(0,2,size=5)
print(x)
print(y)
print(np.allclose(x,y))

[1 1 0 0 1]
[1 1 0 0 1]
True


In [47]:
import numpy as np
x=np.random.random(15)
print(x)
print(x.argmax())
x[x.argmax()]=-1
print(x)

[0.44804325 0.69022952 0.23081228 0.19375552 0.39163956 0.78712277
 0.98378694 0.8057367  0.91034123 0.31304554 0.92503004 0.35033274
 0.81461621 0.71107262 0.24490654]
6
[ 0.44804325  0.69022952  0.23081228  0.19375552  0.39163956  0.78712277
 -1.          0.8057367   0.91034123  0.31304554  0.92503004  0.35033274
  0.81461621  0.71107262  0.24490654]


In [49]:
import numpy as np
a=np.random.random((10,2))
x,y=np.atleast_2d(a[:,0],a[:,1])
d = np.sqrt((x - x.T) ** 2 + (y - y.T) ** 2)
print(d)

[[0.         0.77756932 0.70758989 0.87113215 0.18078385 0.43542328
  0.61455332 0.30285011 0.6094351  0.64509813]
 [0.77756932 0.         0.07574847 0.12899302 0.82733623 0.4646966
  0.63892714 0.68217807 0.38434479 0.39661401]
 [0.70758989 0.07574847 0.         0.20012208 0.75260744 0.38977734
  0.61930265 0.63006427 0.32020365 0.38710107]
 [0.87113215 0.12899302 0.20012208 0.         0.9367846  0.58899537
  0.63633846 0.73742604 0.51313373 0.38941428]
 [0.18078385 0.82733623 0.75260744 0.9367846  0.         0.40507895
  0.77967428 0.47695911 0.57519329 0.774336  ]
 [0.43542328 0.4646966  0.38977734 0.58899537 0.40507895 0.
  0.71789833 0.53893695 0.17521042 0.58450492]
 [0.61455332 0.63892714 0.61930265 0.63633846 0.77967428 0.71789833
  0.         0.31683807 0.80430801 0.24732218]
 [0.30285011 0.68217807 0.63006427 0.73742604 0.47695911 0.53893695
  0.31683807 0.         0.67916488 0.41179745]
 [0.6094351  0.38434479 0.32020365 0.51313373 0.57519329 0.17521042
  0.80430801 0.679164

In [54]:
import numpy as np
x=np.random.randint(1,10,40)
print(x)
print(np.bincount(x).argmax())

[3 4 8 6 4 6 9 7 3 1 8 8 6 6 8 7 8 3 4 9 9 8 8 3 2 7 2 6 6 9 3 6 1 5 1 5 2
 4 7 6]
6


In [55]:
import numpy as np
z=np.random.random((10,2))
x,y=z[:,0],z[:,1]
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
print(r)
print(t)

[0.88928228 1.17093752 0.95433703 1.25205245 1.10843335 0.86804699
 0.75808319 0.23565451 0.76944775 1.17709506]
[0.19944479 0.70637103 0.39450889 0.90365802 1.11361833 0.63655347
 0.86959251 0.58418482 0.94137198 0.5886096 ]


In [63]:
import numpy as np
x=np.arange(0,100)
print(x)
y=np.random.uniform(0,100)
print(y)
index=(np.abs(x-y)).argmin()
print(x[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
7.6264122481297765
8


In [68]:
import numpy as np
x=np.arange(0,10)
print(x)
np.random.shuffle(x)
print(x.max())
n=1
print(x[np.argsort(x)[-n:]])

[0 1 2 3 4 5 6 7 8 9]
9
[9]


In [69]:
import numpy as np
np.random.seed(32)
nums = np.random.randint(low=0, high=256, size=(300, 400, 5), dtype=np.uint8)
print(nums)

[[[215  42 224 219  43]
  [166  69  15 133 255]
  [105  95  54  37 201]
  ...
  [240  22  66 232 132]
  [ 13  85  53 220 170]
  [249  62 221 146  69]]

 [[ 73  79 148 132 164]
  [  3  93  98 138 200]
  [174  34  31 208 130]
  ...
  [ 15 252  41  64  39]
  [188 216 223 124  27]
  [ 85 112 240 116 231]]

 [[227  50 243  20 171]
  [ 12  66 108 102  63]
  [107  54   0   0 173]
  ...
  [215  46  57  99 151]
  [243 199  31  28 179]
  [143   7  30 175 190]]

 ...

 [[214  64  64 212  62]
  [140  44 217  17 164]
  [226 146 247  53 199]
  ...
  [189  68  49 117  63]
  [ 14  17 109  82  92]
  [155 221 135 184 231]]

 [[132 194 160 136 102]
  [132 244 230 117 181]
  [146 245  21 164  29]
  ...
  [125 240 243 190 240]
  [137  41 157 117 155]
  [ 20  92  72 182  41]]

 [[120  45 198 218 190]
  [ 42 150 190 103 106]
  [164  71 220 114  59]
  ...
  [143  20 219 154  85]
  [219 190 170 227 246]
  [ 39  14 127 230 158]]]
