In [1]:
import numpy as np

In [2]:
x=np.array(['Python','PHP'],dtype=np.str_)
y=np.array([' Java',' C++'],dtype=np.str_)
print(np.char.add(x,y))

['Python Java' 'PHP C++']


In [3]:
x=np.array(['Python','Java','C++','PHP'],dtype=np.str_)
print(np.char.multiply(x,3))

['PythonPythonPython' 'JavaJavaJava' 'C++C++C++' 'PHPPHPPHP']


In [4]:
x=np.array(['python','java','C++','PHP'],dtype=np.str_)
print('Capitalized:-',np.char.capitalize(x))
print('Lowered:-',np.char.lower(x))
print('Uppered:-',np.char.upper(x))
print('Swapcases:-',np.char.swapcase(x))
print('Titlecased:-',np.char.title(x))

Capitalized:- ['Python' 'Java' 'C++' 'Php']
Lowered:- ['python' 'java' 'c++' 'php']
Uppered:- ['PYTHON' 'JAVA' 'C++' 'PHP']
Swapcases:- ['PYTHON' 'JAVA' 'c++' 'php']
Titlecased:- ['Python' 'Java' 'C++' 'Php']


In [5]:
x=np.array(['python, exercises', 'PHP', 'java', 'C++'],dtype=np.str_)
print('Centered:=',np.char.center(x,width=15,fillchar='_'))
print('Left:=',np.char.ljust(x,width=15,fillchar='_'))
print('Right:=',np.char.rjust(x,width=15,fillchar='_'))

Centered:= ['python, exercis' '______PHP______' '______java_____' '______C++______']
Left:= ['python, exercis' 'PHP____________' 'java___________' 'C++____________']
Right:= ['python, exercis' '____________PHP' '___________java' '____________C++']


In [6]:
x=np.array(['python, exercises', 'PHP', 'java', 'C++'],dtype=np.str_)
np.char.join(" ", x)

array(['p y t h o n ,   e x e r c i s e s', 'P H P', 'j a v a', 'C + +'],
      dtype='<U33')

In [8]:
x=[b'\x97\xa8\xa3\x88\x96\x95@\x85\xa7\x85\x99\x83\x89\xa2\x85\xa2'
b'\xd7\xc8\xd7' b'\x91\x81\xa5\x81' b'\xc3NN']
y=np.char.decode(x,encoding='cp500')
print(y)
print(np.char.encode(y,'cp500'))

['python exercisesPHPjavaC++']
[b'\x97\xa8\xa3\x88\x96\x95@\x85\xa7\x85\x99\x83\x89\xa2\x85\xa2\xd7\xc8\xd7\x91\x81\xa5\x81\xc3NN']


In [10]:
x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str_)
print(np.char.strip(x))

['python exercises' 'PHP' 'java' 'C++']


In [14]:
x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str_)
print(np.char.lstrip(x))

['python exercises ' 'PHP  ' 'java  ' 'C++']


In [15]:
x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str_)
print(np.char.rstrip(x))

[' python exercises' ' PHP' ' java' '  C++']


In [20]:
x = np.array(['Python PHP Java C++'], dtype=np.str_)
print(np.char.split(x))

[list(['Python', 'PHP', 'Java', 'C++'])]


In [22]:
x = np.array(['Python\\Exercises, Practice, Solution'], dtype=np.str_)
print(np.char.splitlines(x))

[list(['Python\\Exercises, Practice, Solution'])]


In [24]:
x = np.array(['2', '11', '234', '1234', '12345'], dtype=np.str_)
print(np.char.zfill(x,5))

['00002' '00011' '00234' '01234' '12345']


In [28]:
x = np.array(['Python Exercises, Practice, Solution'], dtype=np.str_)
print(np.char.replace(x,'Python','PHP'))

['PHP Exercises, Practice, Solution']


In [34]:
x = np.array(['Hello', 'PHP', 'JS', 'examples', 'html'], dtype=np.str_)
y = np.array(['Hello', 'php', 'Java', 'examples', 'html'], dtype=np.str_)
print('Equal Tests:-',np.char.equal(x,y))
print('Not Equal Tests:-',np.char.not_equal(x,y))
print('Less Equal Tests:-',np.char.less_equal(x,y))
print('Greater Equal Tests:-',np.char.greater_equal(x,y))
print('Less Tests:-',np.char.less(x,y))
print('Greater Tests:-',np.char.greater(x,y))

Equal Tests:- [ True False False  True  True]
Not Equal Tests:- [False  True  True False False]
Less Equal Tests:- [ True  True  True  True  True]
Greater Equal Tests:- [ True False False  True  True]
Less Tests:- [False  True  True False False]
Greater Tests:- [False False False False False]


In [38]:
x = np.array(['Python', 'PHP', 'JS', 'examples', 'html'], dtype=np.str_)
print(np.char.count(x,'P'))

[1 2 0 0 0]


In [40]:
x = np.array(['Python', 'PHP', 'JS', 'EXAMPLES', 'HTML'], dtype=np.str_)
print(np.char.find(x,'P',))

[ 0  0 -1  4 -1]


In [41]:
x = np.array(['Python' ,'PHP', 'JS', 'Examples', 'html5', '5'], dtype=np.str_)
print('Digits Only:-',np.char.isdigit(x))
print('Lower Cases Only:-',np.char.islower(x))
print('Upper Cases Only:-',np.char.isupper(x))

Digits Only:- [False False False False False  True]
Lower Cases Only:- [False False False False  True False]
Upper Cases Only:- [False  True  True False False False]


In [42]:
x = np.array(['Python', 'PHP', 'JS', 'examples', 'html'], dtype=np.str_)
print(np.char.startswith(x,'P'))

[ True  True False False False]


In [43]:
nums = np.array(['1.12', '2.23', '3.71', '4.23', '5.11'], dtype=np.str_)
print(np.char.add('00', nums))
print(np.char.rjust(nums, 6, fillchar='0')) 

['001.12' '002.23' '003.71' '004.23' '005.11']
['001.12' '002.23' '003.71' '004.23' '005.11']


In [50]:
x = np.array([['Python-NumPy-Exercises'],['-Python-']], dtype=np.str_)
print(np.char.strip(np.char.replace(x,'-','==')))
print(np.char.strip(np.char.replace(x,'-',' ')))

[['Python==NumPy==Exercises']
 ['==Python==']]
[['Python NumPy Exercises']
 ['Python']]


In [54]:
x=np.array([['Python', 'NumPy', 'Exercises'],
['Python' ,'Pandas', 'Exercises'],
['Python', 'Machine learning', 'Python']],dtype=np.str_)
print(np.char.count(x,'Python'))

[[1 0 0]
 [1 0 0]
 [1 0 1]]


In [58]:
student = """01	V	Debby Pramod
02	V	Artemiy Ellie
03	V	Baptist Kamal
04	V	Lavanya Davide
05	V	Fulton Antwan
06	V	Euanthe Sandeep
07	V	Endzela Sanda
08	V	Victoire Waman
09	V	Briar Nur
10	V	Rose Lykos"""
print(student)
text_lines = student.splitlines()
text_lines = [r.split('\t') for r in text_lines]
result = np.array(text_lines, dtype=np.str_)
print("\nArray from the said text:")
print(result) 

01	V	Debby Pramod
02	V	Artemiy Ellie
03	V	Baptist Kamal
04	V	Lavanya Davide
05	V	Fulton Antwan
06	V	Euanthe Sandeep
07	V	Endzela Sanda
08	V	Victoire Waman
09	V	Briar Nur
10	V	Rose Lykos

Array from the said text:
[['01' 'V' 'Debby Pramod']
 ['02' 'V' 'Artemiy Ellie']
 ['03' 'V' 'Baptist Kamal']
 ['04' 'V' 'Lavanya Davide']
 ['05' 'V' 'Fulton Antwan']
 ['06' 'V' 'Euanthe Sandeep']
 ['07' 'V' 'Endzela Sanda']
 ['08' 'V' 'Victoire Waman']
 ['09' 'V' 'Briar Nur']
 ['10' 'V' 'Rose Lykos']]
