# TensorFlow 2.x

Tensorflow :- 
- Constant Tensor Array [Immutable Tensor Array]
- Variable Tensor Array [Mutable Tensor Array]
- pip install tensorflow

In [49]:
import tensorflow as tf

In [50]:
tf.__version__

'2.16.1'

# How to Create Constant Tensor Array.

- tf.constant(value,dtype,shape,name)
- zero dimension tensor array/zero rank tensor array

In [51]:
a=tf.constant(10)
a

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [52]:
b=tf.constant(20)
b

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [53]:
c=a+b
c

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [54]:
type(c)

tensorflow.python.framework.ops.EagerTensor

In [55]:
a=tf.constant(20.5)
a

<tf.Tensor: shape=(), dtype=float32, numpy=20.5>

In [56]:
b=tf.constant(40.5)
b

<tf.Tensor: shape=(), dtype=float32, numpy=40.5>

In [57]:
c=a+b
c

<tf.Tensor: shape=(), dtype=float32, numpy=61.0>

In [58]:
a=tf.constant('Welcome to tensorflow')
a

<tf.Tensor: shape=(), dtype=string, numpy=b'Welcome to tensorflow'>

In [59]:
a.dtype

tf.string

In [60]:
a=tf.constant(3+4j)
a

<tf.Tensor: shape=(), dtype=complex128, numpy=(3+4j)>

In [61]:
a=tf.constant(True)
a

<tf.Tensor: shape=(), dtype=bool, numpy=True>

# How to create Constant Tensor Array Using List,Nested List, Numpy Array.

- 1-dimension tensor array

In [62]:
a=tf.constant([2,3,4,5,6,7])
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7])>

In [63]:
a.dtype

tf.int32

In [64]:
a.shape

TensorShape([6])

In [65]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [66]:
b=a.numpy()
b

array([2, 3, 4, 5, 6, 7])

In [67]:
type(b)

numpy.ndarray

In [68]:
b=a.numpy()[3:]
b

array([5, 6, 7])

In [69]:
print(a[2])

tf.Tensor(4, shape=(), dtype=int32)


In [70]:
c=a.numpy().tolist()
c

[2, 3, 4, 5, 6, 7]

In [71]:
type(c)

list

In [72]:
a=tf.constant([2,3,4,5],dtype=tf.float32)
a

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2., 3., 4., 5.], dtype=float32)>

In [73]:
a=tf.constant([2,3,4,5],dtype='float',shape=(2,2))
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [74]:
a.shape

TensorShape([2, 2])

In [75]:
a.dtype

tf.float32

In [76]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [78]:
a=tf.constant([2,3,4,5,6,7],dtype=tf.float32)
a

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([2., 3., 4., 5., 6., 7.], dtype=float32)>

In [81]:
a=tf.constant([2,3,4,5],dtype=tf.float32,shape=(2,2))
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [88]:
a=tf.constant([[2,3],[1,4],[3,5],[6,7]],dtype=tf.float64)
a 

<tf.Tensor: shape=(4, 2), dtype=float64, numpy=
array([[2., 3.],
       [1., 4.],
       [3., 5.],
       [6., 7.]])>

In [89]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [90]:
a.numpy()

array([[2., 3.],
       [1., 4.],
       [3., 5.],
       [6., 7.]])

In [91]:
a.numpy().tolist()

[[2.0, 3.0], [1.0, 4.0], [3.0, 5.0], [6.0, 7.0]]

In [93]:
a.numpy()[1,1]

4.0