# TensorFlow 2.x

Tensorflow :- 
- Constant Tensor Array [Immutable Tensor Array]
- Variable Tensor Array [Mutable Tensor Array]
- pip install tensorflow

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.16.1'

# How to Create Constant Tensor Array.

- tf.constant(value,dtype,shape,name)
- zero dimension tensor array/zero rank tensor array

In [3]:
a=tf.constant(10)
a

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [4]:
b=tf.constant(20)
b

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [5]:
c=a+b
c

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [6]:
type(c)

tensorflow.python.framework.ops.EagerTensor

In [7]:
a=tf.constant(20.5)
a

<tf.Tensor: shape=(), dtype=float32, numpy=20.5>

In [8]:
b=tf.constant(40.5)
b

<tf.Tensor: shape=(), dtype=float32, numpy=40.5>

In [9]:
c=a+b
c

<tf.Tensor: shape=(), dtype=float32, numpy=61.0>

In [10]:
a=tf.constant('Welcome to tensorflow')
a

<tf.Tensor: shape=(), dtype=string, numpy=b'Welcome to tensorflow'>

In [11]:
a.dtype

tf.string

In [12]:
a=tf.constant(3+4j)
a

<tf.Tensor: shape=(), dtype=complex128, numpy=(3+4j)>

In [13]:
a=tf.constant(True)
a

<tf.Tensor: shape=(), dtype=bool, numpy=True>

# How to create Constant Tensor Array Using List,Nested List, Numpy Array.

- 1-dimension tensor array

In [14]:
a=tf.constant([2,3,4,5,6,7])
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7])>

In [15]:
a.dtype

tf.int32

In [16]:
a.shape

TensorShape([6])

In [17]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [18]:
b=a.numpy()
b

array([2, 3, 4, 5, 6, 7])

In [19]:
type(b)

numpy.ndarray

In [20]:
b=a.numpy()[3:]
b

array([5, 6, 7])

In [21]:
print(a[2])

tf.Tensor(4, shape=(), dtype=int32)


In [22]:
c=a.numpy().tolist()
c

[2, 3, 4, 5, 6, 7]

In [23]:
type(c)

list

In [24]:
a=tf.constant([2,3,4,5],dtype=tf.float32)
a

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2., 3., 4., 5.], dtype=float32)>

In [25]:
a=tf.constant([2,3,4,5],dtype='float',shape=(2,2))
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [26]:
a.shape

TensorShape([2, 2])

In [27]:
a.dtype

tf.float32

In [28]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [29]:
a=tf.constant([2,3,4,5,6,7],dtype=tf.float32)
a

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([2., 3., 4., 5., 6., 7.], dtype=float32)>

In [30]:
a=tf.constant([2,3,4,5],dtype=tf.float32,shape=(2,2))
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [31]:
a=tf.constant([[2,3],[1,4],[3,5],[6,7]],dtype=tf.float64)
a 

<tf.Tensor: shape=(4, 2), dtype=float64, numpy=
array([[2., 3.],
       [1., 4.],
       [3., 5.],
       [6., 7.]])>

In [32]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [33]:
a.numpy()

array([[2., 3.],
       [1., 4.],
       [3., 5.],
       [6., 7.]])

In [34]:
a.numpy().tolist()

[[2.0, 3.0], [1.0, 4.0], [3.0, 5.0], [6.0, 7.0]]

In [35]:
a.numpy()[1,1]

4.0

In [36]:
a.numpy()[:,1:2]

array([[3.],
       [4.],
       [5.],
       [7.]])

In [37]:
a=tf.constant([[[2,3],[4,5],[5,6]]],dtype=tf.float32)
a

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[2., 3.],
        [4., 5.],
        [5., 6.]]], dtype=float32)>

In [38]:
a.shape

TensorShape([1, 3, 2])

In [39]:
a[0][1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4., 5.], dtype=float32)>

In [40]:
a[0][-2]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4., 5.], dtype=float32)>

In [41]:
import numpy as np
a=tf.constant(np.array([2,3,4]))
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>

In [42]:
a=tf.constant(np.array([[2,3,4],[5,6,7],[8,9,3]]))
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 3]])>

In [43]:
a=tf.constant(np.array([[[2,3],[4,5],[6,7]]]),dtype=tf.float32)
a

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[2., 3.],
        [4., 5.],
        [6., 7.]]], dtype=float32)>

# Mathematical Operation in Constant Tensor Array.

In [44]:
a=tf.constant([[2,3],[5,6]],tf.float32)
b=tf.constant ([[4,5],[7,8]],tf.float32)
c=tf.add(a,b)
print(c)

tf.Tensor(
[[ 6.  8.]
 [12. 14.]], shape=(2, 2), dtype=float32)


In [45]:
d=tf.subtract(a,b)
d

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2., -2.],
       [-2., -2.]], dtype=float32)>

In [46]:
e=tf.multiply(a,b)
e

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 8., 15.],
       [35., 48.]], dtype=float32)>

In [47]:
f=tf.divide(a,b)
f

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5       , 0.6       ],
       [0.71428573, 0.75      ]], dtype=float32)>

In [48]:
x=tf.matmul(a,b)#Dot Product
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[29., 34.],
       [62., 73.]], dtype=float32)>

In [49]:
print(a@b) # Dot Product

tf.Tensor(
[[29. 34.]
 [62. 73.]], shape=(2, 2), dtype=float32)


In [50]:
print(tf.random.normal([10]))

tf.Tensor(
[ 0.42156577 -0.19106314 -1.1716601  -0.23518945  0.7591955   0.282994
 -1.1531141  -1.2819446   0.31560653  0.37977415], shape=(10,), dtype=float32)


In [51]:
print(tf.random.uniform([10]))

tf.Tensor(
[0.6359643  0.01085079 0.54482234 0.36937833 0.6728399  0.15904105
 0.62557685 0.08191609 0.64818525 0.19445813], shape=(10,), dtype=float32)


In [52]:
print(tf.random.uniform([50],minval=1,maxval=5,dtype=tf.int32))

tf.Tensor(
[1 4 2 1 1 3 3 1 4 3 2 3 1 1 4 3 4 1 1 3 3 4 3 4 2 4 3 3 3 1 4 1 3 3 2 1 1
 1 3 4 2 4 3 3 1 1 1 3 3 2], shape=(50,), dtype=int32)


In [53]:
print(tf.random.uniform([100],minval=1,maxval=10,dtype=tf.int32))

tf.Tensor(
[8 9 9 1 9 8 8 2 1 3 4 6 9 4 5 8 9 3 4 8 7 1 4 4 3 8 8 6 6 6 6 2 5 5 2 8 1
 2 8 5 5 5 6 9 4 9 6 6 3 1 2 2 5 5 9 4 7 6 1 5 9 3 3 4 1 6 5 5 7 5 9 9 1 9
 1 2 5 5 3 6 8 8 4 6 6 3 9 8 4 5 4 8 9 9 4 5 3 3 6 8], shape=(100,), dtype=int32)


In [54]:
x=tf.random.uniform([10],minval=1,maxval=100,dtype=tf.int32)
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([56, 67, 64,  1, 71, 88, 54, 10, 64, 71])>

In [55]:
print(tf.math.reduce_sum(x))

tf.Tensor(546, shape=(), dtype=int32)


In [56]:
print(tf.math.reduce_min(x))

tf.Tensor(1, shape=(), dtype=int32)


In [57]:
print(tf.math.reduce_max(x))

tf.Tensor(88, shape=(), dtype=int32)


In [58]:
print(tf.math.reduce_mean(x))

tf.Tensor(54, shape=(), dtype=int32)


In [59]:
print(tf.math.argmax(x))

tf.Tensor(5, shape=(), dtype=int64)


In [60]:
print(tf.math.argmin(x))

tf.Tensor(3, shape=(), dtype=int64)


# Variable Tensor Array :- (Mutable Tensor Array).

In [61]:
import tensorflow as tf

- tf.Variable(value,dtype,shape,name)

In [62]:
a=tf.Variable(10)
a

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [63]:
type(a)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [64]:
x=tf.Variable([2,3,4,5])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([2, 3, 4, 5])>

In [65]:
type(x)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [66]:
x.shape

TensorShape([4])

In [67]:
x.dtype

tf.int32

In [68]:
x.name

'Variable:0'

In [69]:
x=tf.Variable([2.,3.,4.5,5.6],name='Vector')
x

<tf.Variable 'Vector:0' shape=(4,) dtype=float32, numpy=array([2. , 3. , 4.5, 5.6], dtype=float32)>

In [70]:
x.name

'Vector:0'

In [71]:
x=tf.Variable(['a','b','c','d'])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=string, numpy=array([b'a', b'b', b'c', b'd'], dtype=object)>

In [72]:
x.dtype

tf.string

In [73]:
x=tf.Variable([True,False])
x

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>

In [74]:
x=tf.Variable([3+6j])
x

<tf.Variable 'Variable:0' shape=(1,) dtype=complex128, numpy=array([3.+6.j])>

In [75]:
x.dtype

tf.complex128

In [76]:
x=tf.Variable([2,3,4,5,6],dtype=tf.float32)
x

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([2., 3., 4., 5., 6.], dtype=float32)>

In [77]:
type(x)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [78]:
x.assign([5,9,8,7,6])
x

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([5., 9., 8., 7., 6.], dtype=float32)>

In [79]:
a=tf.constant([2,3,4,5,6])
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6])>

In [80]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [81]:
a.assign([2,3,8,9,10])

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
x=tf.Variable([2,3,4,5,6],dtype=tf.float32)
x

In [ ]:
type(x)

In [ ]:
x.assign([2,5,6,7,8,9]) # Equal len is modify only and same shape is modify different type is not modify)

In [ ]:
x.assign_add([1,2,3,4,5])
x

In [ ]:
x.assign_sub([1,2,3,4,5])
x

In [ ]:
a=tf.constant([[2,3],[4,5],[9,6]])
a

In [ ]:
type(a)

In [ ]:
x=tf.Variable(a) # Change constant array to Variable array
x

In [ ]:
type(x)

In [ ]:
x.numpy()

In [ ]:
tf.argmax(x)

In [ ]:
tf.argmax(x).numpy()

In [ ]:
tf.argmin(x)

In [ ]:
tf.argmin(x).numpy()

In [ ]:
x=tf.Variable([2,3,4,5],dtype=tf.float32)
x

In [ ]:
b=tf.reshape(x,(2,2))
b

In [ ]:
type(b)

In [ ]:
x=tf.Variable([[2,3],[4,5],[5,6]])
x

In [ ]:
type(x)

In [ ]:
y=tf.convert_to_tensor(x)
y

In [ ]:
type(y)

In [ ]:
x=tf.ones(10,dtype=tf.int32)
print(x)

In [ ]:
x=tf.ones((3,2),dtype=tf.int32)
print(x)

In [ ]:
x=tf.ones((2,3,2),dtype=tf.int32)
print(x)

In [ ]:
x.shape

In [ ]:
type(x)

In [ ]:
# tf.ones_Like() 
x=tf.constant([[2,3],[4,5],[6,7]],dtype=tf.float32)
x

In [ ]:
y=tf.ones_like(x,dtype=tf.int32)
y

In [ ]:
a=tf.Variable([[[2,3,4],[4,5,6],[8,9,7]]],dtype=tf.float32)
a

In [ ]:
type(a)

In [ ]:
b=tf.ones_like(a,dtype=tf.int32)
b

In [ ]:
a=tf.zeros(10)
print(a)

In [ ]:
b=tf.zeros((2,3),dtype=tf.int32)
print(b)

In [ ]:
b=tf.zeros((1,3,2),dtype=tf.int32)
print(b)

In [ ]:
x=tf.constant([[2,3],[4,5],[6,7]],dtype=tf.float32)
x

In [ ]:
y=tf.zeros_like(x)
y

In [ ]:
a=tf.fill((3,2),9)
a

In [ ]:
type(a)

In [ ]:
b=tf.fill((3,3),2.5)
b

In [ ]:
c=tf.eye(2)
c

In [ ]:
c=tf.eye(3,2)
c

In [ ]:
d=tf.eye(3,3,dtype=tf.int32,batch_shape=[3])
d

In [ ]:
d=tf.eye(3,3,dtype=tf.int32,batch_shape=[2])
d