# TensorFlow 2.x

Tensorflow :- 
- Constant Tensor Array [Immutable Tensor Array]
- Variable Tensor Array [Mutable Tensor Array]
- pip install tensorflow

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.16.1'

# How to Create Constant Tensor Array.

- tf.constant(value,dtype,shape,name)
- zero dimension tensor array/zero rank tensor array

In [3]:
a=tf.constant(10)
a

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [4]:
b=tf.constant(20)
b

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [5]:
c=a+b
c

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [6]:
type(c)

tensorflow.python.framework.ops.EagerTensor

In [7]:
a=tf.constant(20.5)
a

<tf.Tensor: shape=(), dtype=float32, numpy=20.5>

In [8]:
b=tf.constant(40.5)
b

<tf.Tensor: shape=(), dtype=float32, numpy=40.5>

In [9]:
c=a+b
c

<tf.Tensor: shape=(), dtype=float32, numpy=61.0>

In [10]:
a=tf.constant('Welcome to tensorflow')
a

<tf.Tensor: shape=(), dtype=string, numpy=b'Welcome to tensorflow'>

In [11]:
a.dtype

tf.string

In [12]:
a=tf.constant(3+4j)
a

<tf.Tensor: shape=(), dtype=complex128, numpy=(3+4j)>

In [13]:
a=tf.constant(True)
a

<tf.Tensor: shape=(), dtype=bool, numpy=True>

# How to create Constant Tensor Array Using List,Nested List, Numpy Array.

- 1-dimension tensor array

In [14]:
a=tf.constant([2,3,4,5,6,7])
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7])>

In [15]:
a.dtype

tf.int32

In [16]:
a.shape

TensorShape([6])

In [17]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [18]:
b=a.numpy()
b

array([2, 3, 4, 5, 6, 7])

In [19]:
type(b)

numpy.ndarray

In [20]:
b=a.numpy()[3:]
b

array([5, 6, 7])

In [21]:
print(a[2])

tf.Tensor(4, shape=(), dtype=int32)


In [22]:
c=a.numpy().tolist()
c

[2, 3, 4, 5, 6, 7]

In [23]:
type(c)

list

In [24]:
a=tf.constant([2,3,4,5],dtype=tf.float32)
a

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2., 3., 4., 5.], dtype=float32)>

In [25]:
a=tf.constant([2,3,4,5],dtype='float',shape=(2,2))
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [26]:
a.shape

TensorShape([2, 2])

In [27]:
a.dtype

tf.float32

In [28]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [29]:
a=tf.constant([2,3,4,5,6,7],dtype=tf.float32)
a

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([2., 3., 4., 5., 6., 7.], dtype=float32)>

In [30]:
a=tf.constant([2,3,4,5],dtype=tf.float32,shape=(2,2))
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [31]:
a=tf.constant([[2,3],[1,4],[3,5],[6,7]],dtype=tf.float64)
a 

<tf.Tensor: shape=(4, 2), dtype=float64, numpy=
array([[2., 3.],
       [1., 4.],
       [3., 5.],
       [6., 7.]])>

In [32]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [33]:
a.numpy()

array([[2., 3.],
       [1., 4.],
       [3., 5.],
       [6., 7.]])

In [34]:
a.numpy().tolist()

[[2.0, 3.0], [1.0, 4.0], [3.0, 5.0], [6.0, 7.0]]

In [35]:
a.numpy()[1,1]

4.0

In [36]:
a.numpy()[:,1:2]

array([[3.],
       [4.],
       [5.],
       [7.]])

In [37]:
a=tf.constant([[[2,3],[4,5],[5,6]]],dtype=tf.float32)
a

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[2., 3.],
        [4., 5.],
        [5., 6.]]], dtype=float32)>

In [38]:
a.shape

TensorShape([1, 3, 2])

In [39]:
a[0][1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4., 5.], dtype=float32)>

In [40]:
a[0][-2]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4., 5.], dtype=float32)>

In [42]:
import numpy as np
a=tf.constant(np.array([2,3,4]))
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>

In [43]:
a=tf.constant(np.array([[2,3,4],[5,6,7],[8,9,3]]))
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 3]])>

In [45]:
a=tf.constant(np.array([[[2,3],[4,5],[6,7]]]),dtype=tf.float32)
a

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[2., 3.],
        [4., 5.],
        [6., 7.]]], dtype=float32)>

# Mathematical Operation in Constant Tensor Array.

In [46]:
a=tf.constant([[2,3],[5,6]],tf.float32)
b=tf.constant ([[4,5],[7,8]],tf.float32)
c=tf.add(a,b)
print(c)

tf.Tensor(
[[ 6.  8.]
 [12. 14.]], shape=(2, 2), dtype=float32)


In [47]:
d=tf.subtract(a,b)
d

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2., -2.],
       [-2., -2.]], dtype=float32)>

In [48]:
e=tf.multiply(a,b)
e

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 8., 15.],
       [35., 48.]], dtype=float32)>

In [49]:
f=tf.divide(a,b)
f

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5       , 0.6       ],
       [0.71428573, 0.75      ]], dtype=float32)>

In [52]:
x=tf.matmul(a,b)#Dot Product
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[29., 34.],
       [62., 73.]], dtype=float32)>

In [53]:
print(a@b) # Dot Product

tf.Tensor(
[[29. 34.]
 [62. 73.]], shape=(2, 2), dtype=float32)


In [54]:
print(tf.random.normal([10]))

tf.Tensor(
[ 0.92229974 -1.5831721  -0.27964523 -0.82763875  0.09226442  0.2841891
  0.91798455  1.0361862  -0.44657585 -2.2190862 ], shape=(10,), dtype=float32)


In [55]:
print(tf.random.uniform([10]))

tf.Tensor(
[0.11527002 0.17272091 0.60934186 0.32919466 0.6917199  0.65118134
 0.2876315  0.83195734 0.62423146 0.06336129], shape=(10,), dtype=float32)


In [56]:
print(tf.random.uniform([50],minval=1,maxval=5,dtype=tf.int32))

tf.Tensor(
[2 4 4 2 2 4 1 1 3 3 4 4 1 4 1 1 1 3 1 2 2 2 3 2 2 2 2 4 4 4 4 1 2 2 3 4 3
 2 2 1 4 1 1 3 3 3 3 1 4 3], shape=(50,), dtype=int32)


In [57]:
print(tf.random.uniform([100],minval=1,maxval=10,dtype=tf.int32))

tf.Tensor(
[7 5 6 4 7 8 1 3 5 2 5 9 9 8 6 3 1 9 5 6 6 8 4 3 4 9 9 9 1 4 4 4 7 5 4 8 1
 3 6 5 5 7 7 2 3 5 5 5 1 4 1 4 8 7 4 3 2 3 2 8 2 5 9 8 4 6 7 2 5 3 6 1 8 8
 7 9 9 7 6 8 9 1 3 5 2 3 2 8 4 5 9 5 7 9 2 7 6 5 5 9], shape=(100,), dtype=int32)


In [59]:
x=tf.random.uniform([10],minval=1,maxval=100,dtype=tf.int32)
x

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([64,  5, 45, 66, 92, 27, 17,  7, 97, 30])>

In [61]:
print(tf.math.reduce_sum(x))

tf.Tensor(450, shape=(), dtype=int32)


In [62]:
print(tf.math.reduce_min(x))

tf.Tensor(5, shape=(), dtype=int32)


In [63]:
print(tf.math.reduce_max(x))

tf.Tensor(97, shape=(), dtype=int32)


In [64]:
print(tf.math.reduce_mean(x))

tf.Tensor(45, shape=(), dtype=int32)


In [66]:
print(tf.math.argmax(x))

tf.Tensor(8, shape=(), dtype=int64)


In [67]:
print(tf.math.argmin(x))

tf.Tensor(1, shape=(), dtype=int64)


# Variable Tensor Array :- (Mutable Tensor Array).

In [68]:
import tensorflow as tf

- tf.Variable(value,dtype,shape,name)

In [69]:
a=tf.Variable(10)
a

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [70]:
type(a)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [71]:
x=tf.Variable([2,3,4,5])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([2, 3, 4, 5])>

In [72]:
type(x)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [73]:
x.shape

TensorShape([4])

In [74]:
x.dtype

tf.int32

In [75]:
x.name

'Variable:0'

In [76]:
x=tf.Variable([2.,3.,4.5,5.6],name='Vector')
x

<tf.Variable 'Vector:0' shape=(4,) dtype=float32, numpy=array([2. , 3. , 4.5, 5.6], dtype=float32)>

In [77]:
x.name

'Vector:0'

In [78]:
x=tf.Variable(['a','b','c','d'])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=string, numpy=array([b'a', b'b', b'c', b'd'], dtype=object)>

In [79]:
x.dtype

tf.string

In [80]:
x=tf.Variable([True,False])
x

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>

In [81]:
x=tf.Variable([3+6j])
x

<tf.Variable 'Variable:0' shape=(1,) dtype=complex128, numpy=array([3.+6.j])>

In [82]:
x.dtype

tf.complex128

In [83]:
x=tf.Variable([2,3,4,5,6],dtype=tf.float32)
x

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([2., 3., 4., 5., 6.], dtype=float32)>

In [84]:
type(x)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [86]:
x.assign([5,9,8,7,6])
x

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([5., 9., 8., 7., 6.], dtype=float32)>

In [87]:
a=tf.constant([2,3,4,5,6])
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6])>

In [88]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [89]:
a.assign([2,3,8,9,10])

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [90]:
x=tf.Variable([2,3,4,5,6],dtype=tf.float32)
x

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([2., 3., 4., 5., 6.], dtype=float32)>

In [91]:
type(x)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [93]:
x.assign([2,5,6,7,8,9]) # Equal len is modify only and same shape is modify different type is not modify)

ValueError: Cannot assign value to variable ' Variable:0': Shape mismatch.The variable shape (5,), and the assigned value shape (6,) are incompatible.

In [94]:
x.assign_add([1,2,3,4,5])
x

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([ 3.,  5.,  7.,  9., 11.], dtype=float32)>

In [95]:
x.assign_sub([1,2,3,4,5])
x

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([2., 3., 4., 5., 6.], dtype=float32)>

In [98]:
a=tf.constant([[2,3],[4,5],[9,6]])
a

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5],
       [9, 6]])>

In [99]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [102]:
x=tf.Variable(a) # Change constant array to Variable array
x

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5],
       [9, 6]])>

In [103]:
type(x)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [111]:
x.numpy()

array([[2, 3],
       [4, 5],
       [9, 6]])

In [112]:
tf.argmax(x)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 2], dtype=int64)>

In [113]:
tf.argmax(x).numpy()

array([2, 2], dtype=int64)

In [114]:
tf.argmin(x)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 0], dtype=int64)>

In [115]:
tf.argmin(x).numpy()

array([0, 0], dtype=int64)

In [120]:
x=tf.Variable([2,3,4,5],dtype=tf.float32)
x

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([2., 3., 4., 5.], dtype=float32)>

In [122]:
b=tf.reshape(x,(2,2))
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [123]:
type(b)

tensorflow.python.framework.ops.EagerTensor

In [125]:
x=tf.Variable([[2,3],[4,5],[5,6]])
x

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5],
       [5, 6]])>

In [126]:
type(x)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [127]:
y=tf.convert_to_tensor(x)
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5],
       [5, 6]])>

In [128]:
type(y)

tensorflow.python.framework.ops.EagerTensor

In [131]:
x=tf.ones(10,dtype=tf.int32)
print(x)

tf.Tensor([1 1 1 1 1 1 1 1 1 1], shape=(10,), dtype=int32)


In [132]:
x=tf.ones((3,2),dtype=tf.int32)
print(x)

tf.Tensor(
[[1 1]
 [1 1]
 [1 1]], shape=(3, 2), dtype=int32)


In [136]:
x=tf.ones((2,3,2),dtype=tf.int32)
print(x)

tf.Tensor(
[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]], shape=(2, 3, 2), dtype=int32)


In [137]:
x.shape

TensorShape([2, 3, 2])

In [138]:
type(x)

tensorflow.python.framework.ops.EagerTensor

In [139]:
# tf.ones_Like() 
x=tf.constant([[2,3],[4,5],[6,7]],dtype=tf.float32)
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.],
       [6., 7.]], dtype=float32)>

In [140]:
y=tf.ones_like(x,dtype=tf.int32)
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1],
       [1, 1]])>

In [141]:
a=tf.Variable([[[2,3,4],[4,5,6],[8,9,7]]],dtype=tf.float32)
a

<tf.Variable 'Variable:0' shape=(1, 3, 3) dtype=float32, numpy=
array([[[2., 3., 4.],
        [4., 5., 6.],
        [8., 9., 7.]]], dtype=float32)>

In [142]:
type(a)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [143]:
b=tf.ones_like(a,dtype=tf.int32)
b

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])>

In [146]:
a=tf.zeros(10)
print(a)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)


In [150]:
b=tf.zeros((2,3),dtype=tf.int32)
print(b)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [151]:
b=tf.zeros((1,3,2),dtype=tf.int32)
print(b)

tf.Tensor(
[[[0 0]
  [0 0]
  [0 0]]], shape=(1, 3, 2), dtype=int32)


In [152]:
x=tf.constant([[2,3],[4,5],[6,7]],dtype=tf.float32)
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.],
       [6., 7.]], dtype=float32)>

In [154]:
y=tf.zeros_like(x)
y

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [156]:
a=tf.fill((3,2),9)
a

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[9, 9],
       [9, 9],
       [9, 9]])>

In [157]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [158]:
b=tf.fill((3,3),2.5)
b

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5]], dtype=float32)>

In [159]:
c=tf.eye(2)
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

In [161]:
c=tf.eye(3,2)
c

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [0., 0.]], dtype=float32)>

In [162]:
d=tf.eye(3,3,dtype=tf.int32,batch_shape=[3])
d

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]])>

In [168]:
d=tf.eye(3,3,dtype=tf.int32,batch_shape=[2])
d

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]])>