In [5]:
import numpy as np
z=np.__version__
print(z)
print(np.show_config())

1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/panka/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/panka/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/panka/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/panka/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/panka/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/panka/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/panka/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/panka/anacond

In [6]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [9]:
import numpy as np
x=np.array([1,2,3,4,5,6])
print('Original array:\n',x,sep='')
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x=np.array([0,1,2,3])
print('Original array:\n',x,sep='')
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array:
[1 2 3 4 5 6]
Test if none of the elements of the said array is zero:
True
Original array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False


In [15]:
import numpy as np
x=np.array([1,0,0,0])
print('Original array:\n',x,sep='')
print("Test if none of the elements of the said array is non-zero:")
print(np.any(x))
x=np.array([0,0,0,0])
print('Original array:\n',x,sep='')
print("Test if none of the elements of the said array is non-zero:")
print(np.any(x))

Original array:
[1 0 0 0]
Test if none of the elements of the said array is non-zero:
True
Original array:
[0 0 0 0]
Test if none of the elements of the said array is non-zero:
False


In [12]:
import numpy as np
x=np.array([1,0,np.nan,np.inf])
print('Original array:\n',x,sep='')
print("Test a given array element-wise for finiteness :")
print(np.isfinite(x))

Original array:
[ 1.  0. nan inf]
Test if none of the elements of the said array is zero:
[ True  True False False]


In [13]:
import numpy as np
x=np.array([1,0,np.nan,np.inf])
print('Original array:\n',x,sep='')
print("Test element-wise for positive or negative infinity:")
print(np.isinf(x))

Original array:
[ 1.  0. nan inf]
Test if none of the elements of the said array is zero:
[False False False  True]


In [14]:
import numpy as np
x=np.array([1,0,np.nan,np.inf])
print('Original array:\n',x,sep='')
print("Test element-wise for NaN:")
print(np.isnan(x))

Original array:
[ 1.  0. nan inf]
Test if none of the elements of the said array is zero:
[False False  True False]


In [16]:
import numpy as np
x=np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print('Original array:\n',x,sep='')
print("Checking for complex number:")
print(np.iscomplex(x))
print('Checking for real number:')
print(np.isreal(x))
print("Checking for scalar type:")
print(np.isscalar(3.1))
print(np.isscalar([3.1])) 

Original array:
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number:
[ True False False False False  True]
Checking for real number:
[False  True  True  True  True False]
Checking for scalar type:
True
False


In [17]:
import numpy as np
print("Test if two arrays are element-wise equal within a tolerance:")
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True)) 

Test if two arrays are element-wise equal within a tolerance:
False
True
False
False
True


In [19]:
import numpy as np
x=np.array([3,5])
y=np.array([2,5])
print('Original numbers:')
print(x)
print(y)
print('Comparison -greater')
print(np.greater(x,y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison -greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]
